-- SMLPOS v1.9.2 — Canonical Supabase PostgreSQL schema
-- Run in Supabase Dashboard > SQL Editor (new project or empty database)
-- See supabase/migrations/002_patches.sql for upgrading existing projects

CREATE TABLE IF NOT EXISTS operateurs (id TEXT PRIMARY KEY, nom TEXT NOT NULL, identifiant TEXT UNIQUE NOT NULL, role TEXT DEFAULT 'caissier', actif INTEGER DEFAULT 1, created_at TIMESTAMPTZ DEFAULT NOW());
CREATE TABLE IF NOT EXISTS categories (id TEXT PRIMARY KEY, nom TEXT UNIQUE NOT NULL, icone TEXT);
CREATE TABLE IF NOT EXISTS fournisseurs (id TEXT PRIMARY KEY, nom TEXT NOT NULL, contact_nom TEXT, telephone TEXT, email TEXT, adresse TEXT, matricule_fiscal TEXT, rib TEXT, solde_du FLOAT DEFAULT 0, notes TEXT, actif INTEGER DEFAULT 1, created_at TIMESTAMPTZ DEFAULT NOW());
CREATE TABLE IF NOT EXISTS fournisseur_commerciaux (id TEXT PRIMARY KEY, fournisseur_id TEXT, nom TEXT NOT NULL, telephone TEXT, email TEXT, actif INTEGER DEFAULT 1, created_at TIMESTAMPTZ DEFAULT NOW());
CREATE TABLE IF NOT EXISTS produits (id TEXT PRIMARY KEY, code_barre TEXT UNIQUE, reference TEXT UNIQUE NOT NULL, nom TEXT NOT NULL, description TEXT, categorie TEXT DEFAULT 'Général', categorie_id TEXT, type TEXT DEFAULT 'F', prix_achat FLOAT, prix_vente FLOAT NOT NULL DEFAULT 0, tva_taux FLOAT DEFAULT 0, stock_actuel INTEGER DEFAULT 0, stock_minimum INTEGER DEFAULT 5, fournisseur TEXT, fournisseur_id TEXT, actif INTEGER DEFAULT 1, has_serial_number INTEGER DEFAULT 0, numero_serie TEXT, tva_achat_pct FLOAT DEFAULT 0, marge_pct FLOAT, coef_av FLOAT, cout_supplementaire FLOAT DEFAULT 0, cout_de_revient FLOAT, prix_vente_ht FLOAT, pvp FLOAT, prix_achat_ttc FLOAT, source_tag TEXT, created_at TIMESTAMPTZ DEFAULT NOW(), updated_at TIMESTAMPTZ DEFAULT NOW());
CREATE TABLE IF NOT EXISTS serial_numbers (id TEXT PRIMARY KEY, produit_id TEXT NOT NULL, numero_serie TEXT NOT NULL, statut TEXT DEFAULT 'EN_STOCK', vente_id TEXT, created_at TIMESTAMPTZ DEFAULT NOW(), updated_at TIMESTAMPTZ DEFAULT NOW());
CREATE TABLE IF NOT EXISTS services_pos (id TEXT PRIMARY KEY, nom TEXT NOT NULL, code_barre TEXT UNIQUE NOT NULL, logo_url TEXT, actif INTEGER DEFAULT 1, created_at TIMESTAMPTZ DEFAULT NOW());
CREATE TABLE IF NOT EXISTS transactions_services (id TEXT PRIMARY KEY, shift_id TEXT, service_id TEXT, service_nom TEXT NOT NULL, montant_frais FLOAT NOT NULL, note TEXT, operateur TEXT, created_at TIMESTAMPTZ DEFAULT NOW());
CREATE TABLE IF NOT EXISTS shifts (id TEXT PRIMARY KEY, operateur_id TEXT, operateur_nom TEXT NOT NULL, fond_de_caisse FLOAT NOT NULL, started_at TEXT NOT NULL, ended_at TEXT, total_ventes_especes FLOAT DEFAULT 0, total_services FLOAT DEFAULT 0, total_reparations FLOAT DEFAULT 0, total_credits_recus FLOAT DEFAULT 0, total_sorties FLOAT DEFAULT 0, solde_theorique FLOAT, solde_declare FLOAT, ecart FLOAT, transfere_caisse_interne INTEGER DEFAULT 0, notes_cloture TEXT);
CREATE TABLE IF NOT EXISTS ventes (id TEXT PRIMARY KEY, numero TEXT UNIQUE NOT NULL, shift_id TEXT, operateur_nom TEXT, client_nom TEXT, client_tel TEXT, client_adresse TEXT, client_matricule TEXT, sous_total FLOAT, total_remises FLOAT DEFAULT 0, total_ttc FLOAT NOT NULL, mode_paiement TEXT, montant_recu FLOAT, monnaie_rendue FLOAT DEFAULT 0, type TEXT DEFAULT 'VENTE', type_vente TEXT DEFAULT 'TICKET', a_facture INTEGER DEFAULT 0, statut TEXT DEFAULT 'ACTIVE', annule_par TEXT, annule_at TEXT, annule_motif TEXT, created_at TIMESTAMPTZ DEFAULT NOW());
CREATE TABLE IF NOT EXISTS lignes_vente (id TEXT PRIMARY KEY, vente_id TEXT, produit_id TEXT, designation TEXT NOT NULL, quantite INTEGER NOT NULL, prix_unitaire FLOAT NOT NULL, remise_pct FLOAT DEFAULT 0, total_ligne FLOAT NOT NULL, type_produit TEXT DEFAULT 'F');
CREATE TABLE IF NOT EXISTS factures_clients (id TEXT PRIMARY KEY, numero TEXT UNIQUE NOT NULL, shift_id TEXT, vente_id TEXT, type_facture TEXT DEFAULT 'VENTE_INDIVIDUELLE', client_nom TEXT, client_tel TEXT, client_adresse TEXT, client_matricule TEXT, total_ht FLOAT NOT NULL, total_tva FLOAT DEFAULT 0, total_ttc FLOAT NOT NULL, imprimee INTEGER DEFAULT 0, tva_taux_principal FLOAT, exo TEXT, created_at TIMESTAMPTZ DEFAULT NOW());
CREATE TABLE IF NOT EXISTS reparations (id TEXT PRIMARY KEY, numero TEXT UNIQUE NOT NULL, shift_id TEXT, operateur_nom TEXT, client_nom TEXT, client_tel TEXT, type_appareil TEXT, marque TEXT, modele TEXT, description_panne TEXT, main_oeuvre FLOAT DEFAULT 0, acompte FLOAT DEFAULT 0, total_estime FLOAT DEFAULT 0, total_final FLOAT, statut TEXT DEFAULT 'EN_ATTENTE', technicien TEXT, notes_technicien TEXT, benefice FLOAT, created_at TIMESTAMPTZ DEFAULT NOW(), updated_at TIMESTAMPTZ DEFAULT NOW());
CREATE TABLE IF NOT EXISTS pieces_reparation (id TEXT PRIMARY KEY, reparation_id TEXT, produit_id TEXT, designation TEXT NOT NULL, quantite INTEGER DEFAULT 1, prix_unitaire FLOAT DEFAULT 0, type TEXT DEFAULT 'F');
CREATE TABLE IF NOT EXISTS sorties_caisse (id TEXT PRIMARY KEY, shift_id TEXT, montant FLOAT NOT NULL, note TEXT NOT NULL, operateur TEXT, mouvement_interne_id TEXT, created_at TIMESTAMPTZ DEFAULT NOW());
CREATE TABLE IF NOT EXISTS factures_fournisseurs (id TEXT PRIMARY KEY, numero_facture TEXT NOT NULL, fournisseur_id TEXT, date_facture TEXT NOT NULL, date_echeance TEXT, statut_paiement TEXT DEFAULT 'EN_ATTENTE', montant_ht FLOAT NOT NULL, montant_tva FLOAT DEFAULT 0, montant_ttc FLOAT NOT NULL, montant_paye FLOAT DEFAULT 0, notes TEXT, type TEXT DEFAULT 'FACTURE_ACHAT', statut_reception TEXT DEFAULT 'ARRIVE', exo TEXT, timbre FLOAT DEFAULT 1, ht_7 FLOAT, tva_7 FLOAT, ht_19 FLOAT, tva_19 FLOAT, total_remise FLOAT, created_at TIMESTAMPTZ DEFAULT NOW());
CREATE TABLE IF NOT EXISTS lignes_facture_fournisseur (id TEXT PRIMARY KEY, facture_id TEXT, produit_id TEXT, designation TEXT NOT NULL, quantite INTEGER NOT NULL, ancien_prix_achat FLOAT, nouveau_prix_achat FLOAT NOT NULL, prix_vente_suggere FLOAT, prix_vente_applique FLOAT, tva_taux FLOAT DEFAULT 0);
CREATE TABLE IF NOT EXISTS paiements_fournisseurs (id TEXT PRIMARY KEY, facture_id TEXT, fournisseur_id TEXT, montant FLOAT NOT NULL, mode_paiement TEXT DEFAULT 'ESPECES', reference_cheque TEXT, date_paiement TEXT, notes TEXT, created_at TIMESTAMPTZ DEFAULT NOW());
CREATE TABLE IF NOT EXISTS clients (id TEXT PRIMARY KEY, nom TEXT NOT NULL, telephone TEXT, email TEXT, adresse TEXT, matricule_fiscal TEXT, credit_limite FLOAT DEFAULT 500, solde_credit FLOAT DEFAULT 0, organisation_id TEXT, agent TEXT, actif INTEGER DEFAULT 1, notes TEXT, created_at TIMESTAMPTZ DEFAULT NOW());
CREATE TABLE IF NOT EXISTS credits_clients (id TEXT PRIMARY KEY, client_id TEXT, client_nom TEXT NOT NULL, shift_id TEXT, type TEXT NOT NULL, montant FLOAT NOT NULL, reference TEXT, note TEXT, operateur TEXT, created_at TIMESTAMPTZ DEFAULT NOW());
CREATE TABLE IF NOT EXISTS organisations (id TEXT PRIMARY KEY, nom TEXT NOT NULL, telephone TEXT, email TEXT, adresse TEXT, matricule_fiscal TEXT, credit_total FLOAT DEFAULT 0, notes TEXT, actif INTEGER DEFAULT 1, created_at TIMESTAMPTZ DEFAULT NOW());
CREATE TABLE IF NOT EXISTS personnels (id TEXT PRIMARY KEY, nom TEXT NOT NULL, prenom TEXT, poste TEXT, telephone TEXT, cin TEXT UNIQUE, date_embauche TEXT, salaire_base FLOAT NOT NULL DEFAULT 0, avance_solde FLOAT DEFAULT 0, credit_solde FLOAT DEFAULT 0, actif INTEGER DEFAULT 1, notes TEXT, created_at TIMESTAMPTZ DEFAULT NOW(), updated_at TIMESTAMPTZ DEFAULT NOW());
CREATE TABLE IF NOT EXISTS mouvements_personnels (id TEXT PRIMARY KEY, personnel_id TEXT, type TEXT NOT NULL, montant FLOAT NOT NULL, mois TEXT, note TEXT, operateur TEXT, created_at TIMESTAMPTZ DEFAULT NOW());
CREATE TABLE IF NOT EXISTS documents (id TEXT PRIMARY KEY, numero TEXT UNIQUE NOT NULL, type_document TEXT NOT NULL, statut TEXT DEFAULT 'ACTIF', shift_id TEXT, vente_id TEXT, fournisseur_id TEXT, client_id TEXT, client_nom TEXT, client_tel TEXT, client_adresse TEXT, client_matricule TEXT, total_ht FLOAT NOT NULL DEFAULT 0, total_tva FLOAT DEFAULT 0, total_ttc FLOAT NOT NULL DEFAULT 0, statut_paiement TEXT DEFAULT 'PAYE', montant_paye FLOAT DEFAULT 0, date_echeance TEXT, imprimee INTEGER DEFAULT 0, layout_snapshot TEXT, contenu_json TEXT, exo TEXT, timbre FLOAT DEFAULT 1, ht_7 FLOAT, tva_7 FLOAT, ht_19 FLOAT, tva_19 FLOAT, total_remise FLOAT, tva_taux_principal FLOAT, revoque_par TEXT, revoque_at TEXT, revoque_motif TEXT, reference_source_id TEXT, created_at TIMESTAMPTZ DEFAULT NOW(), updated_at TIMESTAMPTZ DEFAULT NOW());
CREATE TABLE IF NOT EXISTS lignes_document (id TEXT PRIMARY KEY, document_id TEXT, produit_id TEXT, designation TEXT NOT NULL, quantite INTEGER NOT NULL, prix_unitaire FLOAT NOT NULL, remise_pct FLOAT DEFAULT 0, tva_taux FLOAT DEFAULT 0, total_ht FLOAT NOT NULL, total_tva FLOAT DEFAULT 0, total_ttc FLOAT NOT NULL, type_produit TEXT DEFAULT 'F', numero_serie TEXT);
CREATE TABLE IF NOT EXISTS ventes_en_ligne (id TEXT PRIMARY KEY, numero TEXT UNIQUE NOT NULL, shift_id TEXT, operateur_nom TEXT, client_nom TEXT NOT NULL, client_tel TEXT, client_adresse TEXT, produits_json TEXT NOT NULL DEFAULT '[]', montant_ttc FLOAT NOT NULL, montant_net FLOAT, frais_livraison FLOAT DEFAULT 0, frais_retour FLOAT DEFAULT 4, statut TEXT DEFAULT 'EN_ATTENTE', livraison_nom TEXT, montant_recu FLOAT DEFAULT 0, reference_livraison TEXT, note TEXT, created_at TIMESTAMPTZ DEFAULT NOW(), updated_at TIMESTAMPTZ DEFAULT NOW());
CREATE TABLE IF NOT EXISTS retours (id TEXT PRIMARY KEY, vente_id TEXT, vente_numero TEXT, shift_id TEXT, produit_id TEXT, designation TEXT NOT NULL, quantite INTEGER NOT NULL, prix_unitaire FLOAT NOT NULL, motif TEXT, type_retour TEXT NOT NULL, statut TEXT DEFAULT 'EN_ATTENTE', resolution TEXT, montant_rembourse FLOAT DEFAULT 0, operateur TEXT, created_at TIMESTAMPTZ DEFAULT NOW(), updated_at TIMESTAMPTZ DEFAULT NOW());
CREATE TABLE IF NOT EXISTS caisse_interne (id TEXT PRIMARY KEY, date_journal TEXT UNIQUE NOT NULL, solde_ouverture FLOAT NOT NULL DEFAULT 100, total_entrees FLOAT DEFAULT 0, total_sorties FLOAT DEFAULT 0, notes TEXT, created_at TIMESTAMPTZ DEFAULT NOW());
CREATE TABLE IF NOT EXISTS mouvements_caisse_interne (id TEXT PRIMARY KEY, date_journal TEXT NOT NULL, type TEXT NOT NULL, categorie TEXT NOT NULL, montant FLOAT NOT NULL, reference_id TEXT, note TEXT, operateur TEXT DEFAULT 'superadmin', created_at TIMESTAMPTZ DEFAULT NOW());
CREATE TABLE IF NOT EXISTS activity_logs (id TEXT PRIMARY KEY, shift_id TEXT, operateur TEXT, action TEXT NOT NULL, details TEXT DEFAULT '{}', montant FLOAT, created_at TIMESTAMPTZ DEFAULT NOW());
CREATE TABLE IF NOT EXISTS app_settings (key TEXT PRIMARY KEY, value TEXT NOT NULL DEFAULT '', updated_at TIMESTAMPTZ DEFAULT NOW());
CREATE TABLE IF NOT EXISTS sync_queue (id TEXT PRIMARY KEY, table_name TEXT NOT NULL, operation TEXT NOT NULL, payload TEXT NOT NULL, record_id TEXT, attempts INTEGER DEFAULT 0, last_error TEXT, synced_at TIMESTAMPTZ, created_at TIMESTAMPTZ DEFAULT NOW());

DO $$
DECLARE t TEXT;
BEGIN
  FOR t IN SELECT tablename FROM pg_tables WHERE schemaname = 'public'
  LOOP
    EXECUTE 'ALTER TABLE ' || t || ' ENABLE ROW LEVEL SECURITY';
    EXECUTE 'DROP POLICY IF EXISTS allow_all ON ' || t;
    EXECUTE 'CREATE POLICY allow_all ON ' || t || ' FOR ALL USING (true) WITH CHECK (true)';
  END LOOP;
END $$;
